# Used by "mix format"
spark_locals_without_parens = [
  action: 1,
  action: 2,
  add_render_action?: 1,
  as: 1,
  component: 1,
  component: 2,
  component: 3,
  create_action: 1,
  default_preset: 1,
  default_sort: 1,
  field: 1,
  field: 2,
  fields: 1,
  filter: 1,
  filters: 1,
  for_resource: 1,
  format: 1,
  hidden: 1,
  label: 1,
  max_page_size: 1,
  option_label: 1,
  option_limit: 1,
  option_sort: 1,
  option_value: 1,
  order: 1,
  page_size: 1,
  preset: 1,
  preset: 2,
  prompt_fields: 1,
  prompt_title: 1,
  query: 1,
  query: 2,
  read_action: 1,
  refreshes: 1,
  relationship: 1,
  row_actions: 1,
  search_fields: 1,
  sortable: 1,
  source: 1,
  surface_id: 1,
  update_action: 1,
  visible_when: 1,
  widget: 1
]

[
  import_deps: [:ash, :spark],
  inputs: ["{mix,.formatter}.exs", "{config,lib,test}/**/*.{ex,exs}"],
  plugins: [Spark.Formatter],
  locals_without_parens: spark_locals_without_parens,
  export: [
    locals_without_parens: spark_locals_without_parens
  ]
]
