defmodule AshA2ui.Dynamic.Promoter do
  @moduledoc """
  Generates a checked-in standalone UI module (`use AshA2ui.Standalone` with
  an `a2ui do ... end` block) from a validated `AshA2ui.Dynamic` surface
  spec — the "promote to code" step of the spec-as-artifact lifecycle.

  The generated source is formatted (with the extension's own
  `locals_without_parens`, derived from the DSL definition), compile-ready,
  and carries a provenance comment with the spec's content fingerprint.
  Promoting then resolving the generated module produces a surface
  equivalent to resolving the spec directly — the promotion changes *where*
  the declaration lives (reviewable code instead of stored data), never what
  it renders.

  Use through `AshA2ui.Dynamic.to_dsl_source/2`.
  """

  alias AshA2ui.Dynamic.Serializer

  # Spec keys per entity, in emitted order, shaped like the parser's
  # conversions (see AshA2ui.Dynamic.Parser.option_shape/1): the promoter is
  # the parser's inverse, JSON spec values back to DSL literals.
  @component_options [
    fields: :name_list,
    read_action: :name,
    create_action: :name,
    update_action: :name,
    row_actions: :name_list,
    query: :name,
    context_filter: :name_keyword,
    require_context: :name_list,
    select_context: :name,
    context: :name
  ]

  @row_layout_options [
    title: :name,
    badge: :name,
    badge_text: :string_keyword,
    meta: :name_list,
    columns: :raw
  ]

  @group_options [label: :raw, columns: :raw, fields: :name_list]

  @query_options [
    search_fields: :search_fields,
    sortable: :name_list,
    range_filters: :name_list,
    filters: :name_list,
    default_preset: :name,
    default_sort: :default_sort,
    page_size: :raw,
    max_page_size: :raw
  ]

  @preset_options [filter: :raw_keyword, read_action: :name]

  @field_options [
    label: :raw,
    widget: :name,
    format: :name,
    order: :raw,
    hidden: :raw,
    source: :name_list,
    relationship: :name,
    option_label: :name,
    option_value: :name,
    option_sort: :name,
    option_limit: :raw,
    option_search: :name_list
  ]

  @action_options [
    refreshes: :name_list,
    prompt_fields: :name_list,
    prompt_title: :raw,
    visible_when: :raw_keyword
  ]

  @context_options [
    label: :raw,
    option_label: :name,
    option_value: :name,
    option_sort: :name,
    option_limit: :raw,
    option_search: :name_list,
    depends_on: :name,
    depends_on_path: :name_list,
    auto_select_single: :raw,
    picker: :raw
  ]

  @doc """
  Generates the module source for a **pre-validated** spec (callers resolve
  first; see `AshA2ui.Dynamic.to_dsl_source/2`). Returns the formatted
  source string.
  """
  @spec generate(map, module, module, %{String.t() => module}, keyword) :: String.t()
  def generate(spec, module, resource, allowlist, opts) do
    surface_id = Keyword.get_lazy(opts, :surface_id, fn -> default_surface_id(module) end)
    spec_version = Keyword.get(opts, :spec_version, "0.9.1")

    body =
      [
        "for_resource #{inspect(resource)}",
        ~s(surface_id "#{surface_id}"),
        spec_version != "0.9.1" && ~s(spec_version "#{spec_version}"),
        Enum.map(Map.get(spec, "contexts", []), &context_block(&1, allowlist)),
        Enum.map(Map.get(spec, "queries", []), &query_block/1),
        Enum.map(Map.get(spec, "components", []), &component_block/1),
        Enum.map(Map.get(spec, "fields", []), &field_block/1),
        Enum.map(Map.get(spec, "actions", []), &action_block/1)
      ]
      |> List.flatten()
      |> Enum.filter(& &1)

    source = """
    defmodule #{inspect(module)} do
      @moduledoc #{inspect(moduledoc(spec))}

      # Generated by AshA2ui.Dynamic.to_dsl_source/2 from a validated
      # agent-composed surface spec. Provenance:
      #   spec fingerprint: #{Serializer.fingerprint(spec)}
      #   spec format:      #{Serializer.spec_format()}
      #   resource:         #{inspect(resource)}
      use AshA2ui.Standalone

      a2ui do
        #{Enum.join(body, "\n")}
      end
    end
    """

    IO.iodata_to_binary([
      Code.format_string!(source, locals_without_parens: locals_without_parens()),
      "\n"
    ])
  end

  defp moduledoc(spec) do
    title = Map.get(spec, "title")

    [title, "Promoted from an agent-composed `AshA2ui.Dynamic` surface spec."]
    |> Enum.filter(& &1)
    |> Enum.join("\n\n")
  end

  defp default_surface_id(module) do
    module |> Module.split() |> List.last() |> Macro.underscore()
  end

  # --- entity blocks ----------------------------------------------------------------

  defp component_block(entry) do
    args =
      case Map.get(entry, "name") do
        nil -> ":#{Map.fetch!(entry, "kind")}"
        name -> ":#{Map.fetch!(entry, "kind")}, :#{name}"
      end

    nested =
      [
        entry |> Map.get("row_layout") |> row_layout_block(),
        entry |> Map.get("groups", []) |> Enum.map(&group_block/1)
      ]
      |> List.flatten()
      |> Enum.filter(& &1)

    block("component #{args}", option_lines(entry, @component_options) ++ nested)
  end

  defp row_layout_block(nil), do: nil

  defp row_layout_block(entry) do
    block("row_layout", option_lines(entry, @row_layout_options))
  end

  defp group_block(entry) do
    block(~s(group :#{Map.fetch!(entry, "name")}), option_lines(entry, @group_options))
  end

  defp query_block(entry) do
    presets = entry |> Map.get("presets", []) |> Enum.map(&preset_block/1)

    block(
      "query :#{Map.fetch!(entry, "name")}",
      option_lines(entry, @query_options) ++ presets
    )
  end

  defp preset_block(entry) do
    block(~s(preset :#{Map.fetch!(entry, "name")}), option_lines(entry, @preset_options))
  end

  defp field_block(entry) do
    block("field :#{Map.fetch!(entry, "name")}", option_lines(entry, @field_options))
  end

  defp action_block(entry) do
    block("action :#{Map.fetch!(entry, "name")}", option_lines(entry, @action_options))
  end

  defp context_block(entry, allowlist) do
    resource = Map.fetch!(allowlist, Map.fetch!(entry, "resource"))

    block(
      "context :#{Map.fetch!(entry, "name")}",
      ["resource #{inspect(resource)}" | option_lines(entry, @context_options)]
    )
  end

  defp block(header, []), do: header

  defp block(header, lines) do
    "#{header} do\n#{Enum.join(lines, "\n")}\nend"
  end

  defp option_lines(entry, options) do
    for {option, shape} <- options,
        {:ok, value} <- [Map.fetch(entry, to_string(option))] do
      "#{option} #{render(shape, value)}"
    end
  end

  # --- value rendering (the parser's shape conversions, inverted) --------------------

  defp render(:name, value), do: ":#{value}"

  defp render(:name_list, values) do
    "[#{Enum.map_join(values, ", ", &":#{&1}")}]"
  end

  # Keyword-shaped JSON objects are emitted sorted by key — exactly the
  # order AshA2ui.Dynamic.Parser builds them in, so a promoted module
  # resolves to byte-identical entities.
  defp render(:name_keyword, object), do: keyword(object, &render(:name, &1))
  defp render(:raw_keyword, object), do: keyword(object, &render(:raw, &1))
  defp render(:string_keyword, object), do: keyword(object, &render(:raw, &1))

  defp render(:search_fields, values) do
    entries =
      Enum.map_join(values, ", ", fn
        path when is_list(path) -> render(:name_list, path)
        name -> ":#{name}"
      end)

    "[#{entries}]"
  end

  defp render(:default_sort, entries) do
    Enum.map_join(entries, ", ", fn entry ->
      "#{Map.fetch!(entry, "field")}: :#{Map.get(entry, "direction", "asc")}"
    end)
  end

  defp render(:raw, value), do: inspect(value)

  defp keyword(object, render_value) do
    object
    |> Enum.sort()
    |> Enum.map_join(", ", fn {key, value} -> "#{key}: #{render_value.(value)}" end)
  end

  # --- formatter configuration -------------------------------------------------------

  @doc """
  The `locals_without_parens` of the `a2ui` DSL, derived from the extension's
  own section/entity definitions — the same list `mix spark.formatter`
  exports in `.formatter.exs`. Generated sources are formatted with it so
  they are a fixed point of a host project's `mix format`.
  """
  @spec locals_without_parens() :: [{atom, pos_integer}]
  def locals_without_parens do
    [section] = AshA2ui.sections()

    schema_locals(section.schema)
    |> Enum.concat(entity_locals(section.entities))
    |> Enum.uniq()
    |> Enum.sort()
  end

  defp entity_locals(entities) do
    Enum.flat_map(entities, fn entity ->
      nested = entity.entities |> Keyword.values() |> List.flatten()

      builder_locals(entity) ++ schema_locals(entity.schema) ++ entity_locals(nested)
    end)
  end

  # An entity builder is callable with its required args, each optional arg,
  # and optionally a trailing do block: `component :table`, `component
  # :table do`, `component :table, :as do`, ...
  defp builder_locals(entity) do
    required = Enum.count(entity.args, &is_atom/1)
    total = length(entity.args)

    for args <- required..total, block <- 0..1, args + block > 0 do
      {entity.name, args + block}
    end
  end

  defp schema_locals(schema), do: Enum.map(Keyword.keys(schema), &{&1, 1})
end
